### ISSUE TITLE
Cannot save game 'Batman Arkham Asylum '

### ISSUE THREAD

**Issue by pparthenhs** [pallando/gfwl-stripper#1]
Dear all, 

I am facing an issue regarding saving on the game 'Batman Arkham Asylum '.  That game I bought it. Also, I am running windows 10 pro 64-bit.  

It requests to have an account on Games for Windows Live. Unfortunately, this service is not working anymore.

How I could proceed?

Thank you in advance for your help.

Best regards,
P. Parthenis

**Comment by pallando** [comment]
Hello, 

You should be able to use the serial to redeem the GOTY edition on Steam:
https://steamcommunity.com/games/200260/announcements/detail/1909817119598626547

Unless you already own it on Steam, in which case you should already have Arkham Asylum GOTY in your library.

Once you install the GOTY edition, you cannot play old "GFWL" saves, unless you use this unofficial tool (GFWL-stripper) to "convert" your saves (and even that does not always work seemlessly).

**Comment by pparthenhs** [comment]
Hello, 

I am the original CD with the activation key.

I have already tried this. But unfortunately Steam cannot find it. 
_**EDIT by Pallando: image (with potential personal information) has been removed.**_

I am one hundred percent, I am writing the code correctly. 

Thank you again for your help.

Best regards,
P. Parthenis

**Comment by pallando** [comment]
You should try contacting WBSupport, as mentioned in this post for example:
https://steamcommunity.com/app/35140/discussions/0/133259227520946842/#c133259227537140784

There's nothing I can do for you as I don't work for WB Games.

**Comment by pparthenhs** [comment]
I have already try to contacting WBSupport, let's hope for the best.

I would like to thank you again. I really appreciate your help.

Best regards,
P. Parthenis
