### ISSUE TITLE
Resident evil 5

### ISSUE THREAD

**Issue by InactiveCoyote** [pallando/gfwl-stripper#2]
I have tried to use this to use on gfwl save files online but it wont show the game please help

**Comment by pallando** [comment]
Sorry, this tool is only useful for Batman Arkham games actually. 
It looks like the editor made a tool to convert RE5 saves already. 

I have always been curious to see if it would be possible to convert other GFWL saves with this tool by adding an entry to the [Games.ini](https://github.com/pallando/gfwl-stripper/blob/master/Games.ini) file though.

But for that, we need to know how to modify the save file. For Batman games, it was mostly a matter of truncating the beginning of the save (and setting the proper value at the start of the new file).
